(function() {var implementors = {};
implementors["either"] = [{"text":"impl&lt;L, R, A&gt; Extend&lt;A&gt; for Either&lt;L, R&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;L: Extend&lt;A&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;R: Extend&lt;A&gt;,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["futures_util"] = [{"text":"impl&lt;Fut:&nbsp;Future&gt; Extend&lt;Fut&gt; for FuturesOrdered&lt;Fut&gt;","synthetic":false,"types":[]},{"text":"impl&lt;Fut&gt; Extend&lt;Fut&gt; for FuturesUnordered&lt;Fut&gt;","synthetic":false,"types":[]},{"text":"impl&lt;St:&nbsp;Stream + Unpin&gt; Extend&lt;St&gt; for SelectAll&lt;St&gt;","synthetic":false,"types":[]}];
implementors["glib"] = [{"text":"impl Extend&lt;FileTest&gt; for FileTest","synthetic":false,"types":[]},{"text":"impl Extend&lt;FormatSizeFlags&gt; for FormatSizeFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;IOCondition&gt; for IOCondition","synthetic":false,"types":[]},{"text":"impl Extend&lt;KeyFileFlags&gt; for KeyFileFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;LogLevelFlags&gt; for LogLevelFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;OptionFlags&gt; for OptionFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;SpawnFlags&gt; for SpawnFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;BindingFlags&gt; for BindingFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;ParamFlags&gt; for ParamFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;SignalFlags&gt; for SignalFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;LogLevels&gt; for LogLevels","synthetic":false,"types":[]}];
implementors["gstreamer"] = [{"text":"impl Extend&lt;BinFlags&gt; for BinFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;BufferCopyFlags&gt; for BufferCopyFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;BufferFlags&gt; for BufferFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;BufferPoolAcquireFlags&gt; for BufferPoolAcquireFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;ClockFlags&gt; for ClockFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;DebugColorFlags&gt; for DebugColorFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;DebugGraphDetails&gt; for DebugGraphDetails","synthetic":false,"types":[]},{"text":"impl Extend&lt;ElementFlags&gt; for ElementFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;MemoryFlags&gt; for MemoryFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;ObjectFlags&gt; for ObjectFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;PadFlags&gt; for PadFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;PadLinkCheck&gt; for PadLinkCheck","synthetic":false,"types":[]},{"text":"impl Extend&lt;PadProbeType&gt; for PadProbeType","synthetic":false,"types":[]},{"text":"impl Extend&lt;ParseFlags&gt; for ParseFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;PipelineFlags&gt; for PipelineFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;PluginDependencyFlags&gt; for PluginDependencyFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;PluginFlags&gt; for PluginFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;SchedulingFlags&gt; for SchedulingFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;SeekFlags&gt; for SeekFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;SegmentFlags&gt; for SegmentFlags","synthetic":false,"types":[]},{"text":"impl Extend&lt;StreamFlags&gt; for StreamFlags","synthetic":false,"types":[]}];
implementors["proc_macro2"] = [{"text":"impl Extend&lt;TokenTree&gt; for TokenStream","synthetic":false,"types":[]},{"text":"impl Extend&lt;TokenStream&gt; for TokenStream","synthetic":false,"types":[]}];
implementors["syn"] = [{"text":"impl&lt;T, P&gt; Extend&lt;T&gt; for Punctuated&lt;T, P&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;P: Default,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl&lt;T, P&gt; Extend&lt;Pair&lt;T, P&gt;&gt; for Punctuated&lt;T, P&gt;","synthetic":false,"types":[]},{"text":"impl Extend&lt;Error&gt; for Error","synthetic":false,"types":[]}];
implementors["toml"] = [{"text":"impl Extend&lt;(String, Value)&gt; for Map&lt;String, Value&gt;","synthetic":false,"types":[]}];
implementors["vec_map"] = [{"text":"impl&lt;V&gt; Extend&lt;(usize, V)&gt; for VecMap&lt;V&gt;","synthetic":false,"types":[]},{"text":"impl&lt;'a, V:&nbsp;Copy&gt; Extend&lt;(usize, &amp;'a V)&gt; for VecMap&lt;V&gt;","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()