# This workflow only runs on any sequencer prototype changes
# 
# Author: Laurent Brack
name: Rust AI Sequencer Prototype Doc 

on:
  pull_request:
    branches: 
      - main
    paths:
      - 'prototype/**'

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: --enable-index-page -Zunstable-options


jobs:
  check:
    runs-on: ubuntu-18.04
    env:
      working-directory: prototype

    steps:

      - uses: actions/checkout@v2      

      - name: Install Rust Nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          default: true
          # https://blog.rust-lang.org/2019/10/15/Rustup-1.20.0.html#installing-the-latest-compatible-nightly
          profile: default
          components: rustfmt, rust-src

      - name: install other dependencies
        run: |
          sudo apt-get install build-essential gdb pkg-config
          make setup
        working-directory: ${{env.working-directory}}

      - name: Build Docs
        run: |
          make doc doc-dir=../rustdocs
          find ../rustdocs
        working-directory: ${{env.working-directory}}

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./rustdocs/doc