name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --manifest-path prototype/pai-gst-sequencer/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path prototype/pai-gst-sequencer/Cargo.toml      
    - name: Build Docs
      run: cargo doc --manifest-path prototype/pai-gst-sequencer/Cargo.toml --target-dir ./docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/doc