# This workflow only runs on any sequencer prototype changes
# 
# Author: Laurent Brack
name: Rust AI Sequencer Prototype 

on:
  push: 
    paths:
      - 'prototype/**'
  pull_request:
    branches: 
      - main
    paths:
      - 'prototype/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-18.04
    env:
      working-directory: prototype

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt-get install build-essential gdb pkg-config
        make setup
      working-directory: ${{env.working-directory}}

    - name: Build
      run: make build
      working-directory: ${{env.working-directory}}

    - name: Run tests
      run: make test
      working-directory: ${{env.working-directory}}

    - name: Build Docs
      run: make doc target-dir ../../docs
      working-directory: ${{env.working-directory}}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/doc