# This workflow only runs on any sequencer prototype changes
# 
# Author: Laurent Brack
name: AI Sequencer Proto Rust Build

on:
  push: 
    paths:
      - 'prototype/**'
  pull_request:
    branches: 
      - main
    paths:
      - 'prototype/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-18.04
    env:
      working-directory: prototype

    steps:

      - uses: actions/checkout@v2      

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: periscopai
          token: ${{ secrets.TESTSPACE_TOKEN }}   
          
      - name: Add local bin to path
        run: |
          echo "/home/runner/.local/bin" >> $GITHUB_PATH
 

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt, rust-src

      - name: install other dependencies
        run: |
          sudo apt-get install build-essential gdb pkg-config
          make setup
          cargo install cargo2junit
        working-directory: ${{env.working-directory}}

      - name: Build Sequencer
        run: make build project=pai-gst-sequencer
        working-directory: ${{env.working-directory}}

      - name: Build RocketAI
        run: make build project=pai-gst-sequencer
        working-directory: ${{env.working-directory}}


      - name: Running Sequencer Rust Test
        run: make test project=pai-gst-sequencer
        working-directory: ${{env.working-directory}}

      - name: Running Rocket AI Rust Test
        run: make test project=rocketai
        working-directory: ${{env.working-directory}}

      - name: Run Pytest
        run: make pytest
        continue-on-error: true
        working-directory: ${{env.working-directory}}

      - name: Push Rust results to Testspace server
        run: |
          testspace xunit-*.xml
        working-directory: ${{env.working-directory}}
        if: always()        


      - name: Build Docs
        run: make doc doc-dir=../../autogen
        working-directory: ${{env.working-directory}}
